// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weather32Api.Data;

#nullable disable

namespace Weather32Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260502115511_AddStationsAndFeatures")]
    partial class AddStationsAndFeatures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Weather32Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 2, 11, 55, 9, 921, DateTimeKind.Utc).AddTicks(5552),
                            Email = "pucdolf@example.com",
                            Password = "password",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 5, 2, 11, 55, 9, 921, DateTimeKind.Utc).AddTicks(6119),
                            Username = "Pucdolf"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 2, 11, 55, 9, 921, DateTimeKind.Utc).AddTicks(6662),
                            Email = "pgkuba@example.com",
                            Password = "1234",
                            Role = "User",
                            UpdatedAt = new DateTime(2026, 5, 2, 11, 55, 9, 921, DateTimeKind.Utc).AddTicks(6663),
                            Username = "PGKuba"
                        });
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float?>("DSTemperatureF")
                        .HasColumnType("real");

                    b.Property<float?>("DSTemperatureK")
                        .HasColumnType("real");

                    b.Property<float?>("DhtTemperatureC")
                        .HasColumnType("real");

                    b.Property<float?>("DhtTemperatureF")
                        .HasColumnType("real");

                    b.Property<float?>("DhtTemperatureK")
                        .HasColumnType("real");

                    b.Property<float?>("DsTemperatureC")
                        .HasColumnType("real");

                    b.Property<float?>("Humidity")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeatherStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeatherStationId");

                    b.ToTable("WeatherRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DSTemperatureF = 74.8f,
                            DSTemperatureK = 296.9f,
                            DhtTemperatureC = 24.5f,
                            DhtTemperatureF = 76.1f,
                            DhtTemperatureK = 297.6f,
                            DsTemperatureC = 23.8f,
                            Humidity = 45f,
                            TimeStamp = new DateTime(2024, 3, 18, 8, 30, 0, 0, DateTimeKind.Utc),
                            WeatherStationId = 0
                        },
                        new
                        {
                            Id = 2,
                            DSTemperatureF = 75.6f,
                            DSTemperatureK = 297.3f,
                            DhtTemperatureC = 25.1f,
                            DhtTemperatureF = 77.2f,
                            DhtTemperatureK = 298.2f,
                            DsTemperatureC = 24.2f,
                            Humidity = 42f,
                            TimeStamp = new DateTime(2024, 3, 18, 12, 45, 12, 0, DateTimeKind.Utc),
                            WeatherStationId = 0
                        },
                        new
                        {
                            Id = 3,
                            DSTemperatureF = 75.2f,
                            DSTemperatureK = 297.1f,
                            DhtTemperatureC = 24.8f,
                            DhtTemperatureF = 76.6f,
                            DhtTemperatureK = 297.9f,
                            DsTemperatureC = 24f,
                            Humidity = 44f,
                            TimeStamp = new DateTime(2024, 3, 19, 9, 15, 20, 0, DateTimeKind.Utc),
                            WeatherStationId = 0
                        },
                        new
                        {
                            Id = 4,
                            DSTemperatureF = 74.3f,
                            DSTemperatureK = 296.6f,
                            DhtTemperatureC = 24.2f,
                            DhtTemperatureF = 75.6f,
                            DhtTemperatureK = 297.3f,
                            DsTemperatureC = 23.5f,
                            Humidity = 46f,
                            TimeStamp = new DateTime(2024, 3, 19, 18, 20, 30, 0, DateTimeKind.Utc),
                            WeatherStationId = 0
                        },
                        new
                        {
                            Id = 5,
                            DSTemperatureF = 73.8f,
                            DSTemperatureK = 296.3f,
                            DhtTemperatureC = 23.9f,
                            DhtTemperatureF = 75f,
                            DhtTemperatureK = 297f,
                            DsTemperatureC = 23.2f,
                            Humidity = 47f,
                            TimeStamp = new DateTime(2024, 3, 20, 7, 10, 45, 0, DateTimeKind.Utc),
                            WeatherStationId = 0
                        });
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WeatherStations");
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherStationFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeatherStationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WeatherStationId");

                    b.ToTable("WeatherStationFeatures");
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherData", b =>
                {
                    b.HasOne("Weather32Api.Models.WeatherStation", "WeatherStation")
                        .WithMany("WeatherRecords")
                        .HasForeignKey("WeatherStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherStation", b =>
                {
                    b.HasOne("Weather32Api.Models.User", "User")
                        .WithMany("WeatherStations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherStationFeatures", b =>
                {
                    b.HasOne("Weather32Api.Models.WeatherStation", "WeatherStation")
                        .WithMany("Features")
                        .HasForeignKey("WeatherStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeatherStation");
                });

            modelBuilder.Entity("Weather32Api.Models.User", b =>
                {
                    b.Navigation("WeatherStations");
                });

            modelBuilder.Entity("Weather32Api.Models.WeatherStation", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("WeatherRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
